### ISSUE TITLE
First Incite of the Map

### ISSUE THREAD

**Issue by Anouar0000** [Anouar0000/TozarGameDev#1]
Create map :

- [x] Sandy ground, Rocky ground.
- [x] Mountains
- [x] Mosque
- [x] Pyramide
- [x] Houses
- [x] Hole houses, Carved in mountains 
- [x] Palm Trees
- [x] Plants

**Comment by aymen-cyber** [comment]
@Anouar0000 
Ani jit

**Comment by Anouar0000** [comment]
![image](https://github.com/Anouar0000/TozarGameDev/assets/66185555/9821474e-c604-4b64-a31a-16e60978786e)

haw 3malt platform

**Comment by Anouar0000** [comment]
![Image](https://github.com/Anouar0000/TozarGameDev/assets/66185555/278bca68-310a-40e2-a4ee-ab5f0be87d1f)

**Comment by Anouar0000** [comment]
How the house

![Image](https://github.com/Anouar0000/TozarGameDev/assets/66185555/f0e1c8a4-685d-4b4f-a260-46022a3312f5)

na3ref plain ama to being with, 3andi models o5rin ken yelzem ne5dem bihom.

**Comment by Anouar0000** [comment]
![Image](https://github.com/Anouar0000/TozarGameDev/assets/66185555/91df16a2-0f3b-4992-90ab-83d08f6bf261)

**Comment by Anouar0000** [comment]
![Image](https://github.com/Anouar0000/TozarGameDev/assets/66185555/9db40509-7684-4a88-9dba-609a15a06c8a)

**Comment by Anouar0000** [comment]
![Image](https://github.com/Anouar0000/TozarGameDev/assets/66185555/3c76c200-6197-48b7-8772-01f8de12b1eb)

**Comment by Anouar0000** [comment]
pyramide w dyar fel hit mich bech na3malhom tawa
